services:
  postgres:
    restart: on-failure
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /usr/local/docker/postgres:/var/lib/postgresql/data